
create  TABLE Fact(Nums INT) 
INSERT INTO Fact SELECT 0 UNION ALL
 SELECT 1 UNION ALL 
 SELECT 3 UNION ALL
  SELECT 5 UNION ALL
   SELECT 10 
   
   SELECT * FROM Fact 


/*--main query--*/

   ;WITH CTE_FACT AS
(
       SELECT 0 AS NUMS, 1 AS FACTORIAL
       UNION ALL
       SELECT NUMS+1, FACTORIAL*(NUMS+1)
       FROM CTE_FACT
       WHERE NUMS < 10
)
SELECT DISTINCT NUMS, FACTORIAL
FROM CTE_FACT    
WHERE NUMS IN (SELECT Nums FROM Fact)